version: "2"
services:
  node-server:
    container_name: node-server
    build: {context: ./docker/node-server, dockerfile: Dockerfile}
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./public/node-server/hello-world/:/home/node/app
    ports: ['8080:8080']
    command: "npm run dev"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
  apache-php7-server:
    build: {context: ./docker/apache-php7-server, dockerfile: Dockerfile}
    container_name: apache-php7-server
    ports:
      - '80:80'
    volumes:
      - ./public/htdocs:/var/www/html
