version: "2"
services:
  node-server:
    container_name: node-server
    build: {context: ./docker/node-server, dockerfile: Dockerfile}
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./public/node-server/hello-world/:/home/node/app
    ports: ['8080:8080']
    command: "npm start"
